server:
      port: 8090
      servlet:
            context-path: /api
spring:
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/eiasiscon
        username: postgres
        password: 2010
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        
api:
   security:
         jwt:
            tokenExpirationTime: 240 # Number of minutes
            refreshTokenExpTime: 540 # Minutes
            tokenIssuer: eiasiscon.com.br
            tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAws
logging.level:
    org.springframework: INFO
    com.zaxxer: ERROR
    root: ERROR